config/routes.rb
Rails.application.routes.draw do

  resources :cities do
    resources :shops
  end

  root 'welcome#index'
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :shops, dependent: :destroy
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end
  def new
    @city = City.new
  end
  def create
    @city = City.create!(city_params)

    redirect_to city_path(@city)
  end
  def show
    @city = City.find(params[:id])
    @shops = @city.shops.all
  end
  private
  def city_params
    params.require(:city).permit(:cityname)
  end
end

app/controllers/concerns/data_controller.rb
class DataController < ApplicationController

  def enter
  end

  def show_data
    @properties = params[:properties] || []
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    # @cities = City.all
    @city = City.find(params[:city_id])
    @shops = @city.shops.all


  end
  def new
    @city = City.find(params[:city_id])
    @shop = @city.shops.new
  end
  def create
    @city = City.find(params[:city_id])
    @shop = @city.shops.create!(shop_params.merge(params['shop']))
    #WORKAROUND:  why is properties unpermitted?
     redirect_to city_shop_path(@city, @shop)

  end




  def show
    @city = City.find(params[:city_id])
    @shop = @city.shops.all


  # if params[:properties].present?
  #    @shop = @city.shops.all

  #   end
    # redirect_to city_shop_path
  end

  def edit
    @city = City.find(params[:city_id])
    @shop = @city.shops.find(params[:id])
  end

  def update
    @city = City.find(params[:city_id])
    @shop = @city.shops.find(params[:id])
    @shop.update(shop_params)

    redirect_to city_shops_path
  end







  def destroy
  @city = City.find(params[:city_id])
  @shop = Shop.find(params[:id])
  @shop.destroy

  redirect_to city_shops_path
  end
  private
  def shop_params
    params.require(:shop).permit(:shopname, :location, :properties, :city_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <div class="div_top">

    <h1 class="titles">How you brewin?</h1>
  </div>

      <div class="citylist">

        <% @cities.each do |city| %>
        <%= link_to city.cityname, city_path(city) %></br>

        <% end %>


      <div class="links">
        <h2 align="center"><div class="button"><%= link_to 'Home', root_path %></div><h2>
          <h2 align="center"><div class="button"><%= link_to 'Add City', new_city_path %></div><h2>
          </div>
          </div>
    </body>
    </html>

app/views/cities/new.html.erb
<h1>New City Page</h1>
<div class="links">
<h2 align="center"><div class="button"><%= link_to 'Home', root_path %></div><h2>
</div>

<%= form_for @city do |f| %>
  <p>
    <%= f.label :cityname %><br>
    <%= f.text_field :cityname %>
  </p>

  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/cities/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <div class="div_top">



</div>
    <div>
      <h1><%= @city.cityname %></h1>
      <% @shops.each do |shop| %>
      <div class="shop">
        <p class="shopname"><%= shop.shopname %></br></p>
        <div class="properties">
        <% shop.properties.each do |property_name, property_value| %>

        <p data-supports='<%= property_value %>'>
          <%= property_name %>
        </p>
        <% end %>
      </br>
    </div>
    <% end %>

  </div>



  <div class="links">

    <h2 align="center"><div class="button"><%= link_to 'Add City', new_city_path %></div><h2>

      <h2 align="center"><div class="button"><%= link_to 'Back to Cities', cities_path %></div><h2>

        <h2 align="center"><div class="button"><%= link_to 'Add Coffee Shop', new_city_shop_path(@city) %></div><h2>
        </div>

      </body>
      </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thejavahunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shops/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="div_top">
    <h1>Edit Coffee Shop</h1>
  </div>
    <div class="form">
    <%= form_for [@city, @shop] do |f| %>
      <p>
        <%= f.label :shopname %><br>
        <%= f.text_field :shopname %>
      </p>

      <!-- <p><%= f.hidden_field(:city_id, value: @city.id) %></p> -->
      <p>
        <li class="coffeeproperties">
          <input type="checkbox" value="1" name="shop[properties][Wifi]" id="shop_properties"> Wifi
          <input type="checkbox" value="1" name="shop[properties][Outdoor Seating]" id="shop_properties"> Outdoor Seating
          <input type="checkbox" value="1" name="shop[properties][Iced Coffee]" id="shop_properties"> Iced Coffee
          <input type="checkbox" value="1" name="shop[properties][Music]" id="shop_properties"> Music
          <input type="checkbox" value="1" name="shop[properties][Soy Milk]" id="shop_properties"> Soy Milk </br>
          <input type="checkbox" value="1" name="shop[properties][Sandwiches]" id="shop_properties"> Sandwiches
          <input type="checkbox" value="1" name="shop[properties][Doughnuts]" id="shop_properties"> Doughnuts
          <input type="checkbox" value="1" name="shop[properties][Fruit]" id="shop_properties"> Fruit
          <input type="checkbox" value="1" name="shop[properties][Free Refills]" id="shop_properties"> Free Refills
          <input type="checkbox" value="1" name="shop[properties][Flavored Coffee]" id="shop_properties"> Flavored Coffee
          <input type="checkbox" value="1" name="shop[properties][Alcohol]" id="shop_properties"> Alcohol
       </li>
      </p>

      <p>

        <%= f.submit %>

      </p>
    <% end %>
    <%= form_for [@city, @shop], method: :delete do |f| %>
      <%= f.submit "Delete", :class => "form-button" %>
      <% end %>
    </div>


    <div class="links">
    <h2 align="center"><div class="button"><%= link_to 'Coffee Shops Index', city_shop_path %></div><h2>
    </div>

  </body>
</html>

app/views/shops/index.html.erb
<h1 align="center">Under construction</h1>


<div class="shoplist">

<h2 align="center"><div class="button"><%= link_to 'City list', city_path(@city) %></div><h2>
</div>

  <h1 align="center"> <img src="https://media.giphy.com/media/OMeGDxdAsMPzW/giphy.gif" alt="COnstruction" class="construction"/></h1>

app/views/shops/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="div_top">

  </div>
    <div class="form">
    <%= form_for [@city, @shop] do |f| %>
      <p>
        <%= f.label :shopname %><br>
        <%= f.text_field :shopname %>
      </p>

      <li class="coffeeproperties">
        <input type="checkbox" value="true" name="shop[properties][Wifi]" id="shop_properties"> Wifi
        <input type="checkbox" value="true" name="shop[properties][Outdoor Seating]" id="shop_properties"> Outdoor Seating
        <input type="checkbox" value="true" name="shop[properties][Iced Coffee]" id="shop_properties"> Iced Coffee
        <input type="checkbox" value="true" name="shop[properties][Music]" id="shop_properties"> Music
        <input type="checkbox" value="true" name="shop[properties][Soy Milk]" id="shop_properties"> Soy Milk </br>
        <input type="checkbox" value="true" name="shop[properties][Sandwiches]" id="shop_properties"> Sandwiches
        <input type="checkbox" value="true" name="shop[properties][Doughnuts]" id="shop_properties"> Doughnuts
        <input type="checkbox" value="true" name="shop[properties][Fruit]" id="shop_properties"> Fruit
        <input type="checkbox" value="true" name="shop[properties][Free Refills]" id="shop_properties"> Free Refills
        <input type="checkbox" value="true" name="shop[properties][Flavored Coffee]" id="shop_properties"> Flavored Coffee
        <input type="checkbox" value="true" name="shop[properties][Alcohol]" id="shop_properties"> Alcohol
     </li>
        <%= f.submit %>
      </p>
    <% end %>
    </div>
    <div class="links">
    <h2 align="center"><div class="button"><%= link_to 'Coffee Shops', city_shops_path %></div><h2>
      <h2 align="center"><div class="button"><%= link_to 'Home', root_path %></div><h2>
    </div>

  </body>
</html>

app/views/shops/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="div_top">
    <h1></h1>
  </div>
    <div class="links">

    <h2 align="center"><div class="button"><%= link_to 'Java Hunt', cities_path %></div><h2>

    <h2 align="center"><div class="button"><%= link_to 'Home', root_path %></div><h2>

      <h2 align="center"><div class="button"><%= link_to 'Edit Coffee Shop', edit_city_shop_path %></div><h2>
      </div>

    </div>



    <% @shop.each do |shop| %>
    <div class="shop">
    <p class="shopname">Shop: <%= shop.shopname %> </p>
    <div class="properties">
    <% shop.properties.each do |property_name, property_value| %>

    <p data-supports='<%= property_value %>'>
      <%= property_name %>
    </p>
    <% end %>
    </br>
    <% end %>
  </div>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <h1 class="JavaHunt">JAVA HUNT</h1>
    <h2 class="brewin">how you brewin?</h2>

    <h1 align="center"> <img src="https://media.giphy.com/media/inECjKmGYzGms/giphy.gif" alt="Coffee" class="coffeegif"/></h1>

    <div class="links">
    <h2 align="center"><div class="button"><%= link_to 'Start Hunting', cities_path %></div><h2>
    </div>
  </body>
</html>